// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scheduler.proto

/*
Package mesos_v1_scheduler is a generated protocol buffer package.

It is generated from these files:
	scheduler.proto

It has these top-level messages:
	Event
	Response
	Call
*/
package mesos_v1_scheduler

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import mesos_v1 "github.com/mesos/go-proto/mesos/v1"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Possible event types, followed by message definitions if
// applicable.
type Event_Type int32

const (
	// This must be the first enum value in this list, to
	// ensure that if 'type' is not set, the default value
	// is UNKNOWN. This enables enum values to be added
	// in a backwards-compatible way. See: MESOS-4997.
	Event_UNKNOWN                 Event_Type = 0
	Event_SUBSCRIBED              Event_Type = 1
	Event_OFFERS                  Event_Type = 2
	Event_INVERSE_OFFERS          Event_Type = 9
	Event_RESCIND                 Event_Type = 3
	Event_RESCIND_INVERSE_OFFER   Event_Type = 10
	Event_UPDATE                  Event_Type = 4
	Event_UPDATE_OPERATION_STATUS Event_Type = 11
	Event_MESSAGE                 Event_Type = 5
	Event_FAILURE                 Event_Type = 6
	Event_ERROR                   Event_Type = 7
	// Periodic message sent by the Mesos master according to
	// 'Subscribed.heartbeat_interval_seconds'. If the scheduler does
	// not receive any events (including heartbeats) for an extended
	// period of time (e.g., 5 x heartbeat_interval_seconds), there is
	// likely a network partition. In such a case the scheduler should
	// close the existing subscription connection and resubscribe
	// using a backoff strategy.
	Event_HEARTBEAT Event_Type = 8
)

var Event_Type_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "SUBSCRIBED",
	2:  "OFFERS",
	9:  "INVERSE_OFFERS",
	3:  "RESCIND",
	10: "RESCIND_INVERSE_OFFER",
	4:  "UPDATE",
	11: "UPDATE_OPERATION_STATUS",
	5:  "MESSAGE",
	6:  "FAILURE",
	7:  "ERROR",
	8:  "HEARTBEAT",
}
var Event_Type_value = map[string]int32{
	"UNKNOWN":                 0,
	"SUBSCRIBED":              1,
	"OFFERS":                  2,
	"INVERSE_OFFERS":          9,
	"RESCIND":                 3,
	"RESCIND_INVERSE_OFFER":   10,
	"UPDATE":                  4,
	"UPDATE_OPERATION_STATUS": 11,
	"MESSAGE":                 5,
	"FAILURE":                 6,
	"ERROR":                   7,
	"HEARTBEAT":               8,
}

func (x Event_Type) Enum() *Event_Type {
	p := new(Event_Type)
	*p = x
	return p
}
func (x Event_Type) String() string {
	return proto.EnumName(Event_Type_name, int32(x))
}
func (x *Event_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Event_Type_value, data, "Event_Type")
	if err != nil {
		return err
	}
	*x = Event_Type(value)
	return nil
}
func (Event_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// Each of the responses of type `FOO` corresponds to `Foo` message below.
type Response_Type int32

const (
	Response_UNKNOWN              Response_Type = 0
	Response_RECONCILE_OPERATIONS Response_Type = 1
)

var Response_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "RECONCILE_OPERATIONS",
}
var Response_Type_value = map[string]int32{
	"UNKNOWN":              0,
	"RECONCILE_OPERATIONS": 1,
}

func (x Response_Type) Enum() *Response_Type {
	p := new(Response_Type)
	*p = x
	return p
}
func (x Response_Type) String() string {
	return proto.EnumName(Response_Type_name, int32(x))
}
func (x *Response_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Response_Type_value, data, "Response_Type")
	if err != nil {
		return err
	}
	*x = Response_Type(value)
	return nil
}
func (Response_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

// Possible call types, followed by message definitions if
// applicable.
type Call_Type int32

const (
	// See comments above on `Event::Type` for more details on this enum value.
	Call_UNKNOWN                      Call_Type = 0
	Call_SUBSCRIBE                    Call_Type = 1
	Call_TEARDOWN                     Call_Type = 2
	Call_ACCEPT                       Call_Type = 3
	Call_DECLINE                      Call_Type = 4
	Call_ACCEPT_INVERSE_OFFERS        Call_Type = 13
	Call_DECLINE_INVERSE_OFFERS       Call_Type = 14
	Call_REVIVE                       Call_Type = 5
	Call_KILL                         Call_Type = 6
	Call_SHUTDOWN                     Call_Type = 7
	Call_ACKNOWLEDGE                  Call_Type = 8
	Call_ACKNOWLEDGE_OPERATION_STATUS Call_Type = 15
	Call_RECONCILE                    Call_Type = 9
	Call_RECONCILE_OPERATIONS         Call_Type = 16
	Call_MESSAGE                      Call_Type = 10
	Call_REQUEST                      Call_Type = 11
	Call_SUPPRESS                     Call_Type = 12
)

var Call_Type_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "SUBSCRIBE",
	2:  "TEARDOWN",
	3:  "ACCEPT",
	4:  "DECLINE",
	13: "ACCEPT_INVERSE_OFFERS",
	14: "DECLINE_INVERSE_OFFERS",
	5:  "REVIVE",
	6:  "KILL",
	7:  "SHUTDOWN",
	8:  "ACKNOWLEDGE",
	15: "ACKNOWLEDGE_OPERATION_STATUS",
	9:  "RECONCILE",
	16: "RECONCILE_OPERATIONS",
	10: "MESSAGE",
	11: "REQUEST",
	12: "SUPPRESS",
}
var Call_Type_value = map[string]int32{
	"UNKNOWN":                      0,
	"SUBSCRIBE":                    1,
	"TEARDOWN":                     2,
	"ACCEPT":                       3,
	"DECLINE":                      4,
	"ACCEPT_INVERSE_OFFERS":        13,
	"DECLINE_INVERSE_OFFERS":       14,
	"REVIVE":                       5,
	"KILL":                         6,
	"SHUTDOWN":                     7,
	"ACKNOWLEDGE":                  8,
	"ACKNOWLEDGE_OPERATION_STATUS": 15,
	"RECONCILE":                    9,
	"RECONCILE_OPERATIONS":         16,
	"MESSAGE":                      10,
	"REQUEST":                      11,
	"SUPPRESS":                     12,
}

func (x Call_Type) Enum() *Call_Type {
	p := new(Call_Type)
	*p = x
	return p
}
func (x Call_Type) String() string {
	return proto.EnumName(Call_Type_name, int32(x))
}
func (x *Call_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Call_Type_value, data, "Call_Type")
	if err != nil {
		return err
	}
	*x = Call_Type(value)
	return nil
}
func (Call_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

// *
// Scheduler event API.
//
// An event is described using the standard protocol buffer "union"
// trick, see:
// https://developers.google.com/protocol-buffers/docs/techniques#union.
type Event struct {
	// Type of the event, indicates which optional field below should be
	// present if that type has a nested message definition.
	// Enum fields should be optional, see: MESOS-4997.
	Type                  *Event_Type                  `protobuf:"varint,1,opt,name=type,enum=mesos.v1.scheduler.Event_Type" json:"type,omitempty"`
	Subscribed            *Event_Subscribed            `protobuf:"bytes,2,opt,name=subscribed" json:"subscribed,omitempty"`
	Offers                *Event_Offers                `protobuf:"bytes,3,opt,name=offers" json:"offers,omitempty"`
	InverseOffers         *Event_InverseOffers         `protobuf:"bytes,9,opt,name=inverse_offers,json=inverse_offers" json:"inverse_offers,omitempty"`
	Rescind               *Event_Rescind               `protobuf:"bytes,4,opt,name=rescind" json:"rescind,omitempty"`
	RescindInverseOffer   *Event_RescindInverseOffer   `protobuf:"bytes,10,opt,name=rescind_inverse_offer,json=rescind_inverse_offer" json:"rescind_inverse_offer,omitempty"`
	Update                *Event_Update                `protobuf:"bytes,5,opt,name=update" json:"update,omitempty"`
	UpdateOperationStatus *Event_UpdateOperationStatus `protobuf:"bytes,11,opt,name=update_operation_status,json=update_operation_status" json:"update_operation_status,omitempty"`
	Message               *Event_Message               `protobuf:"bytes,6,opt,name=message" json:"message,omitempty"`
	Failure               *Event_Failure               `protobuf:"bytes,7,opt,name=failure" json:"failure,omitempty"`
	Error                 *Event_Error                 `protobuf:"bytes,8,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized      []byte                       `json:"-"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Event) GetType() Event_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Event_UNKNOWN
}

func (m *Event) GetSubscribed() *Event_Subscribed {
	if m != nil {
		return m.Subscribed
	}
	return nil
}

func (m *Event) GetOffers() *Event_Offers {
	if m != nil {
		return m.Offers
	}
	return nil
}

func (m *Event) GetInverseOffers() *Event_InverseOffers {
	if m != nil {
		return m.InverseOffers
	}
	return nil
}

func (m *Event) GetRescind() *Event_Rescind {
	if m != nil {
		return m.Rescind
	}
	return nil
}

func (m *Event) GetRescindInverseOffer() *Event_RescindInverseOffer {
	if m != nil {
		return m.RescindInverseOffer
	}
	return nil
}

func (m *Event) GetUpdate() *Event_Update {
	if m != nil {
		return m.Update
	}
	return nil
}

func (m *Event) GetUpdateOperationStatus() *Event_UpdateOperationStatus {
	if m != nil {
		return m.UpdateOperationStatus
	}
	return nil
}

func (m *Event) GetMessage() *Event_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Event) GetFailure() *Event_Failure {
	if m != nil {
		return m.Failure
	}
	return nil
}

func (m *Event) GetError() *Event_Error {
	if m != nil {
		return m.Error
	}
	return nil
}

// First event received when the scheduler subscribes.
type Event_Subscribed struct {
	FrameworkId *mesos_v1.FrameworkID `protobuf:"bytes,1,req,name=framework_id,json=framework_id" json:"framework_id,omitempty"`
	// This value will be set if the master is sending heartbeats. See
	// the comment above on 'HEARTBEAT' for more details.
	HeartbeatIntervalSeconds *float64 `protobuf:"fixed64,2,opt,name=heartbeat_interval_seconds,json=heartbeat_interval_seconds" json:"heartbeat_interval_seconds,omitempty"`
	// Since Mesos 1.1.
	MasterInfo       *mesos_v1.MasterInfo `protobuf:"bytes,3,opt,name=master_info,json=master_info" json:"master_info,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *Event_Subscribed) Reset()                    { *m = Event_Subscribed{} }
func (m *Event_Subscribed) String() string            { return proto.CompactTextString(m) }
func (*Event_Subscribed) ProtoMessage()               {}
func (*Event_Subscribed) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Event_Subscribed) GetFrameworkId() *mesos_v1.FrameworkID {
	if m != nil {
		return m.FrameworkId
	}
	return nil
}

func (m *Event_Subscribed) GetHeartbeatIntervalSeconds() float64 {
	if m != nil && m.HeartbeatIntervalSeconds != nil {
		return *m.HeartbeatIntervalSeconds
	}
	return 0
}

func (m *Event_Subscribed) GetMasterInfo() *mesos_v1.MasterInfo {
	if m != nil {
		return m.MasterInfo
	}
	return nil
}

// Received whenever there are new resources that are offered to the
// scheduler. Each offer corresponds to a set of resources on an
// agent. Until the scheduler accepts or declines an offer the
// resources are considered allocated to the scheduler.
type Event_Offers struct {
	Offers           []*mesos_v1.Offer `protobuf:"bytes,1,rep,name=offers" json:"offers,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Event_Offers) Reset()                    { *m = Event_Offers{} }
func (m *Event_Offers) String() string            { return proto.CompactTextString(m) }
func (*Event_Offers) ProtoMessage()               {}
func (*Event_Offers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *Event_Offers) GetOffers() []*mesos_v1.Offer {
	if m != nil {
		return m.Offers
	}
	return nil
}

// Received whenever there are resources requested back from the
// scheduler. Each inverse offer specifies the agent, and
// optionally specific resources. Accepting or Declining an inverse
// offer informs the allocator of the scheduler's ability to release
// the specified resources without violating an SLA. If no resources
// are specified then all resources on the agent are requested to be
// released.
type Event_InverseOffers struct {
	InverseOffers    []*mesos_v1.InverseOffer `protobuf:"bytes,1,rep,name=inverse_offers,json=inverse_offers" json:"inverse_offers,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *Event_InverseOffers) Reset()                    { *m = Event_InverseOffers{} }
func (m *Event_InverseOffers) String() string            { return proto.CompactTextString(m) }
func (*Event_InverseOffers) ProtoMessage()               {}
func (*Event_InverseOffers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 2} }

func (m *Event_InverseOffers) GetInverseOffers() []*mesos_v1.InverseOffer {
	if m != nil {
		return m.InverseOffers
	}
	return nil
}

// Received when a particular offer is no longer valid (e.g., the
// agent corresponding to the offer has been removed) and hence
// needs to be rescinded. Any future calls ('Accept' / 'Decline') made
// by the scheduler regarding this offer will be invalid.
type Event_Rescind struct {
	OfferId          *mesos_v1.OfferID `protobuf:"bytes,1,req,name=offer_id,json=offer_id" json:"offer_id,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Event_Rescind) Reset()                    { *m = Event_Rescind{} }
func (m *Event_Rescind) String() string            { return proto.CompactTextString(m) }
func (*Event_Rescind) ProtoMessage()               {}
func (*Event_Rescind) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 3} }

func (m *Event_Rescind) GetOfferId() *mesos_v1.OfferID {
	if m != nil {
		return m.OfferId
	}
	return nil
}

// Received when a particular inverse offer is no longer valid
// (e.g., the agent corresponding to the offer has been removed)
// and hence needs to be rescinded. Any future calls ('Accept' /
// 'Decline') made by the scheduler regarding this inverse offer
// will be invalid.
type Event_RescindInverseOffer struct {
	InverseOfferId   *mesos_v1.OfferID `protobuf:"bytes,1,req,name=inverse_offer_id,json=inverse_offer_id" json:"inverse_offer_id,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Event_RescindInverseOffer) Reset()                    { *m = Event_RescindInverseOffer{} }
func (m *Event_RescindInverseOffer) String() string            { return proto.CompactTextString(m) }
func (*Event_RescindInverseOffer) ProtoMessage()               {}
func (*Event_RescindInverseOffer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 4} }

func (m *Event_RescindInverseOffer) GetInverseOfferId() *mesos_v1.OfferID {
	if m != nil {
		return m.InverseOfferId
	}
	return nil
}

// Received whenever there is a status update that is generated by
// the executor or agent or master. Status updates should be used by
// executors to reliably communicate the status of the tasks that
// they manage. It is crucial that a terminal update (see TaskState
// in v1/mesos.proto) is sent by the executor as soon as the task
// terminates, in order for Mesos to release the resources allocated
// to the task. It is also the responsibility of the scheduler to
// explicitly acknowledge the receipt of a status update. See
// 'Acknowledge' in the 'Call' section below for the semantics.
//
// A task status update may be used for guaranteed delivery of some
// task-related information, e.g., task's health update. Such
// information may be shadowed by subsequent task status updates, that
// do not preserve fields of the previously sent message.
type Event_Update struct {
	Status           *mesos_v1.TaskStatus `protobuf:"bytes,1,req,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *Event_Update) Reset()                    { *m = Event_Update{} }
func (m *Event_Update) String() string            { return proto.CompactTextString(m) }
func (*Event_Update) ProtoMessage()               {}
func (*Event_Update) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 5} }

func (m *Event_Update) GetStatus() *mesos_v1.TaskStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// Received when there is an operation status update generated by the
// master, agent, or resource provider. These updates are only sent to
// the framework for operations which had the operation ID set by the
// framework. It is the responsibility of the scheduler to explicitly
// acknowledge the receipt of a status update.
// See 'AcknowledgeOperationStatus' in the 'Call' section below for
// the semantics.
type Event_UpdateOperationStatus struct {
	Status           *mesos_v1.OperationStatus `protobuf:"bytes,1,req,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *Event_UpdateOperationStatus) Reset()                    { *m = Event_UpdateOperationStatus{} }
func (m *Event_UpdateOperationStatus) String() string            { return proto.CompactTextString(m) }
func (*Event_UpdateOperationStatus) ProtoMessage()               {}
func (*Event_UpdateOperationStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 6} }

func (m *Event_UpdateOperationStatus) GetStatus() *mesos_v1.OperationStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// Received when a custom message generated by the executor is
// forwarded by the master. Note that this message is not
// interpreted by Mesos and is only forwarded (without reliability
// guarantees) to the scheduler. It is up to the executor to retry
// if the message is dropped for any reason.
type Event_Message struct {
	AgentId          *mesos_v1.AgentID    `protobuf:"bytes,1,req,name=agent_id,json=agent_id" json:"agent_id,omitempty"`
	ExecutorId       *mesos_v1.ExecutorID `protobuf:"bytes,2,req,name=executor_id,json=executor_id" json:"executor_id,omitempty"`
	Data             []byte               `protobuf:"bytes,3,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *Event_Message) Reset()                    { *m = Event_Message{} }
func (m *Event_Message) String() string            { return proto.CompactTextString(m) }
func (*Event_Message) ProtoMessage()               {}
func (*Event_Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 7} }

func (m *Event_Message) GetAgentId() *mesos_v1.AgentID {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *Event_Message) GetExecutorId() *mesos_v1.ExecutorID {
	if m != nil {
		return m.ExecutorId
	}
	return nil
}

func (m *Event_Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// Received when an agent is removed from the cluster (e.g., failed
// health checks) or when an executor is terminated. Note that, this
// event coincides with receipt of terminal UPDATE events for any
// active tasks belonging to the agent or executor and receipt of
// 'Rescind' events for any outstanding offers belonging to the
// agent. Note that there is no guaranteed order between the
// 'Failure', 'Update' and 'Rescind' events when an agent or executor
// is removed.
// TODO(vinod): Consider splitting the lost agent and terminated
// executor into separate events and ensure it's reliably generated.
type Event_Failure struct {
	AgentId *mesos_v1.AgentID `protobuf:"bytes,1,opt,name=agent_id,json=agent_id" json:"agent_id,omitempty"`
	// If this was just a failure of an executor on an agent then
	// 'executor_id' will be set and possibly 'status' (if we were
	// able to determine the exit status).
	ExecutorId *mesos_v1.ExecutorID `protobuf:"bytes,2,opt,name=executor_id,json=executor_id" json:"executor_id,omitempty"`
	// On Posix, `status` corresponds to termination information in the
	// `stat_loc` area returned from a `waitpid` call. On Windows, `status`
	// is obtained via calling the `GetExitCodeProcess()` function. For
	// messages coming from Posix agents, schedulers need to apply
	// `WEXITSTATUS` family macros or equivalent transformations to obtain
	// exit codes.
	//
	// TODO(alexr): Consider unifying Windows and Posix behavior by returning
	// exit code here, see MESOS-7241.
	Status           *int32 `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Event_Failure) Reset()                    { *m = Event_Failure{} }
func (m *Event_Failure) String() string            { return proto.CompactTextString(m) }
func (*Event_Failure) ProtoMessage()               {}
func (*Event_Failure) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 8} }

func (m *Event_Failure) GetAgentId() *mesos_v1.AgentID {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *Event_Failure) GetExecutorId() *mesos_v1.ExecutorID {
	if m != nil {
		return m.ExecutorId
	}
	return nil
}

func (m *Event_Failure) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

// Received when there is an unrecoverable error in the scheduler (e.g.,
// scheduler failed over, rate limiting, authorization errors etc.). The
// scheduler should abort on receiving this event.
type Event_Error struct {
	Message          *string `protobuf:"bytes,1,req,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Event_Error) Reset()                    { *m = Event_Error{} }
func (m *Event_Error) String() string            { return proto.CompactTextString(m) }
func (*Event_Error) ProtoMessage()               {}
func (*Event_Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 9} }

func (m *Event_Error) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

// *
// Synchronous responses for calls made to the scheduler API.
type Response struct {
	ReconcileOperations *Response_ReconcileOperations `protobuf:"bytes,1,opt,name=reconcile_operations,json=reconcile_operations" json:"reconcile_operations,omitempty"`
	XXX_unrecognized    []byte                        `json:"-"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetReconcileOperations() *Response_ReconcileOperations {
	if m != nil {
		return m.ReconcileOperations
	}
	return nil
}

type Response_ReconcileOperations struct {
	OperationStatuses []*mesos_v1.OperationStatus `protobuf:"bytes,1,rep,name=operation_statuses,json=operation_statuses" json:"operation_statuses,omitempty"`
	XXX_unrecognized  []byte                      `json:"-"`
}

func (m *Response_ReconcileOperations) Reset()                    { *m = Response_ReconcileOperations{} }
func (m *Response_ReconcileOperations) String() string            { return proto.CompactTextString(m) }
func (*Response_ReconcileOperations) ProtoMessage()               {}
func (*Response_ReconcileOperations) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *Response_ReconcileOperations) GetOperationStatuses() []*mesos_v1.OperationStatus {
	if m != nil {
		return m.OperationStatuses
	}
	return nil
}

// *
// Scheduler call API.
//
// Like Event, a Call is described using the standard protocol buffer
// "union" trick (see above).
type Call struct {
	// Identifies who generated this call. Master assigns a framework id
	// when a new scheduler subscribes for the first time. Once assigned,
	// the scheduler must set the 'framework_id' here and within its
	// FrameworkInfo (in any further 'Subscribe' calls). This allows the
	// master to identify a scheduler correctly across disconnections,
	// failovers, etc.
	FrameworkId *mesos_v1.FrameworkID `protobuf:"bytes,1,opt,name=framework_id,json=framework_id" json:"framework_id,omitempty"`
	// Type of the call, indicates which optional field below should be
	// present if that type has a nested message definition.
	// See comments on `Event::Type` above on the reasoning behind this
	// field being optional.
	Type                       *Call_Type                       `protobuf:"varint,2,opt,name=type,enum=mesos.v1.scheduler.Call_Type" json:"type,omitempty"`
	Subscribe                  *Call_Subscribe                  `protobuf:"bytes,3,opt,name=subscribe" json:"subscribe,omitempty"`
	Accept                     *Call_Accept                     `protobuf:"bytes,4,opt,name=accept" json:"accept,omitempty"`
	Decline                    *Call_Decline                    `protobuf:"bytes,5,opt,name=decline" json:"decline,omitempty"`
	AcceptInverseOffers        *Call_AcceptInverseOffers        `protobuf:"bytes,13,opt,name=accept_inverse_offers,json=accept_inverse_offers" json:"accept_inverse_offers,omitempty"`
	DeclineInverseOffers       *Call_DeclineInverseOffers       `protobuf:"bytes,14,opt,name=decline_inverse_offers,json=decline_inverse_offers" json:"decline_inverse_offers,omitempty"`
	Revive                     *Call_Revive                     `protobuf:"bytes,15,opt,name=revive" json:"revive,omitempty"`
	Kill                       *Call_Kill                       `protobuf:"bytes,6,opt,name=kill" json:"kill,omitempty"`
	Shutdown                   *Call_Shutdown                   `protobuf:"bytes,7,opt,name=shutdown" json:"shutdown,omitempty"`
	Acknowledge                *Call_Acknowledge                `protobuf:"bytes,8,opt,name=acknowledge" json:"acknowledge,omitempty"`
	AcknowledgeOperationStatus *Call_AcknowledgeOperationStatus `protobuf:"bytes,17,opt,name=acknowledge_operation_status,json=acknowledge_operation_status" json:"acknowledge_operation_status,omitempty"`
	Reconcile                  *Call_Reconcile                  `protobuf:"bytes,9,opt,name=reconcile" json:"reconcile,omitempty"`
	ReconcileOperations        *Call_ReconcileOperations        `protobuf:"bytes,18,opt,name=reconcile_operations,json=reconcile_operations" json:"reconcile_operations,omitempty"`
	Message                    *Call_Message                    `protobuf:"bytes,10,opt,name=message" json:"message,omitempty"`
	Request                    *Call_Request                    `protobuf:"bytes,11,opt,name=request" json:"request,omitempty"`
	Suppress                   *Call_Suppress                   `protobuf:"bytes,16,opt,name=suppress" json:"suppress,omitempty"`
	XXX_unrecognized           []byte                           `json:"-"`
}

func (m *Call) Reset()                    { *m = Call{} }
func (m *Call) String() string            { return proto.CompactTextString(m) }
func (*Call) ProtoMessage()               {}
func (*Call) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Call) GetFrameworkId() *mesos_v1.FrameworkID {
	if m != nil {
		return m.FrameworkId
	}
	return nil
}

func (m *Call) GetType() Call_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Call_UNKNOWN
}

func (m *Call) GetSubscribe() *Call_Subscribe {
	if m != nil {
		return m.Subscribe
	}
	return nil
}

func (m *Call) GetAccept() *Call_Accept {
	if m != nil {
		return m.Accept
	}
	return nil
}

func (m *Call) GetDecline() *Call_Decline {
	if m != nil {
		return m.Decline
	}
	return nil
}

func (m *Call) GetAcceptInverseOffers() *Call_AcceptInverseOffers {
	if m != nil {
		return m.AcceptInverseOffers
	}
	return nil
}

func (m *Call) GetDeclineInverseOffers() *Call_DeclineInverseOffers {
	if m != nil {
		return m.DeclineInverseOffers
	}
	return nil
}

func (m *Call) GetRevive() *Call_Revive {
	if m != nil {
		return m.Revive
	}
	return nil
}

func (m *Call) GetKill() *Call_Kill {
	if m != nil {
		return m.Kill
	}
	return nil
}

func (m *Call) GetShutdown() *Call_Shutdown {
	if m != nil {
		return m.Shutdown
	}
	return nil
}

func (m *Call) GetAcknowledge() *Call_Acknowledge {
	if m != nil {
		return m.Acknowledge
	}
	return nil
}

func (m *Call) GetAcknowledgeOperationStatus() *Call_AcknowledgeOperationStatus {
	if m != nil {
		return m.AcknowledgeOperationStatus
	}
	return nil
}

func (m *Call) GetReconcile() *Call_Reconcile {
	if m != nil {
		return m.Reconcile
	}
	return nil
}

func (m *Call) GetReconcileOperations() *Call_ReconcileOperations {
	if m != nil {
		return m.ReconcileOperations
	}
	return nil
}

func (m *Call) GetMessage() *Call_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Call) GetRequest() *Call_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Call) GetSuppress() *Call_Suppress {
	if m != nil {
		return m.Suppress
	}
	return nil
}

// Subscribes the scheduler with the master to receive events. A
// scheduler must send other calls only after it has received the
// SUBCRIBED event.
type Call_Subscribe struct {
	// See the comments below on 'framework_id' on the semantics for
	// 'framework_info.id'.
	FrameworkInfo *mesos_v1.FrameworkInfo `protobuf:"bytes,1,req,name=framework_info,json=framework_info" json:"framework_info,omitempty"`
	// List of suppressed roles for which the framework does not wish to be
	// offered resources. The framework can decide to suppress all or a subset
	// of roles the framework (re)registers as.
	SuppressedRoles  []string `protobuf:"bytes,2,rep,name=suppressed_roles,json=suppressed_roles" json:"suppressed_roles,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Call_Subscribe) Reset()                    { *m = Call_Subscribe{} }
func (m *Call_Subscribe) String() string            { return proto.CompactTextString(m) }
func (*Call_Subscribe) ProtoMessage()               {}
func (*Call_Subscribe) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *Call_Subscribe) GetFrameworkInfo() *mesos_v1.FrameworkInfo {
	if m != nil {
		return m.FrameworkInfo
	}
	return nil
}

func (m *Call_Subscribe) GetSuppressedRoles() []string {
	if m != nil {
		return m.SuppressedRoles
	}
	return nil
}

// Accepts an offer, performing the specified operations
// in a sequential manner.
//
// E.g. Launch a task with a newly reserved persistent volume:
//
//   Accept {
//     offer_ids: [ ... ]
//     operations: [
//       { type: RESERVE,
//         reserve: { resources: [ disk(role):2 ] } }
//       { type: CREATE,
//         create: { volumes: [ disk(role):1+persistence ] } }
//       { type: LAUNCH,
//         launch: { task_infos ... disk(role):1;disk(role):1+persistence } }
//     ]
//   }
//
// Note that any of the offer’s resources not used in the 'Accept'
// call (e.g., to launch a task) are considered unused and might be
// reoffered to other frameworks. In other words, the same OfferID
// cannot be used in more than one 'Accept' call.
type Call_Accept struct {
	OfferIds         []*mesos_v1.OfferID         `protobuf:"bytes,1,rep,name=offer_ids,json=offer_ids" json:"offer_ids,omitempty"`
	Operations       []*mesos_v1.Offer_Operation `protobuf:"bytes,2,rep,name=operations" json:"operations,omitempty"`
	Filters          *mesos_v1.Filters           `protobuf:"bytes,3,opt,name=filters" json:"filters,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *Call_Accept) Reset()                    { *m = Call_Accept{} }
func (m *Call_Accept) String() string            { return proto.CompactTextString(m) }
func (*Call_Accept) ProtoMessage()               {}
func (*Call_Accept) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 1} }

func (m *Call_Accept) GetOfferIds() []*mesos_v1.OfferID {
	if m != nil {
		return m.OfferIds
	}
	return nil
}

func (m *Call_Accept) GetOperations() []*mesos_v1.Offer_Operation {
	if m != nil {
		return m.Operations
	}
	return nil
}

func (m *Call_Accept) GetFilters() *mesos_v1.Filters {
	if m != nil {
		return m.Filters
	}
	return nil
}

// Declines an offer, signaling the master to potentially reoffer
// the resources to a different framework. Note that this is same
// as sending an Accept call with no operations. See comments on
// top of 'Accept' for semantics.
type Call_Decline struct {
	OfferIds         []*mesos_v1.OfferID `protobuf:"bytes,1,rep,name=offer_ids,json=offer_ids" json:"offer_ids,omitempty"`
	Filters          *mesos_v1.Filters   `protobuf:"bytes,2,opt,name=filters" json:"filters,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Call_Decline) Reset()                    { *m = Call_Decline{} }
func (m *Call_Decline) String() string            { return proto.CompactTextString(m) }
func (*Call_Decline) ProtoMessage()               {}
func (*Call_Decline) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 2} }

func (m *Call_Decline) GetOfferIds() []*mesos_v1.OfferID {
	if m != nil {
		return m.OfferIds
	}
	return nil
}

func (m *Call_Decline) GetFilters() *mesos_v1.Filters {
	if m != nil {
		return m.Filters
	}
	return nil
}

// Accepts an inverse offer. Inverse offers should only be accepted
// if the resources in the offer can be safely evacuated before the
// provided unavailability.
type Call_AcceptInverseOffers struct {
	InverseOfferIds  []*mesos_v1.OfferID `protobuf:"bytes,1,rep,name=inverse_offer_ids,json=inverse_offer_ids" json:"inverse_offer_ids,omitempty"`
	Filters          *mesos_v1.Filters   `protobuf:"bytes,2,opt,name=filters" json:"filters,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Call_AcceptInverseOffers) Reset()                    { *m = Call_AcceptInverseOffers{} }
func (m *Call_AcceptInverseOffers) String() string            { return proto.CompactTextString(m) }
func (*Call_AcceptInverseOffers) ProtoMessage()               {}
func (*Call_AcceptInverseOffers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 3} }

func (m *Call_AcceptInverseOffers) GetInverseOfferIds() []*mesos_v1.OfferID {
	if m != nil {
		return m.InverseOfferIds
	}
	return nil
}

func (m *Call_AcceptInverseOffers) GetFilters() *mesos_v1.Filters {
	if m != nil {
		return m.Filters
	}
	return nil
}

// Declines an inverse offer. Inverse offers should be declined if
// the resources in the offer might not be safely evacuated before
// the provided unavailability.
type Call_DeclineInverseOffers struct {
	InverseOfferIds  []*mesos_v1.OfferID `protobuf:"bytes,1,rep,name=inverse_offer_ids,json=inverse_offer_ids" json:"inverse_offer_ids,omitempty"`
	Filters          *mesos_v1.Filters   `protobuf:"bytes,2,opt,name=filters" json:"filters,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Call_DeclineInverseOffers) Reset()                    { *m = Call_DeclineInverseOffers{} }
func (m *Call_DeclineInverseOffers) String() string            { return proto.CompactTextString(m) }
func (*Call_DeclineInverseOffers) ProtoMessage()               {}
func (*Call_DeclineInverseOffers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 4} }

func (m *Call_DeclineInverseOffers) GetInverseOfferIds() []*mesos_v1.OfferID {
	if m != nil {
		return m.InverseOfferIds
	}
	return nil
}

func (m *Call_DeclineInverseOffers) GetFilters() *mesos_v1.Filters {
	if m != nil {
		return m.Filters
	}
	return nil
}

// Revive offers for the specified roles. If `roles` is empty,
// the `REVIVE` call will revive offers for all of the roles
// the framework is currently subscribed to.
type Call_Revive struct {
	Roles            []string `protobuf:"bytes,1,rep,name=roles" json:"roles,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Call_Revive) Reset()                    { *m = Call_Revive{} }
func (m *Call_Revive) String() string            { return proto.CompactTextString(m) }
func (*Call_Revive) ProtoMessage()               {}
func (*Call_Revive) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 5} }

func (m *Call_Revive) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

// Kills a specific task. If the scheduler has a custom executor,
// the kill is forwarded to the executor and it is up to the
// executor to kill the task and send a TASK_KILLED (or TASK_FAILED)
// update. Note that Mesos releases the resources for a task once it
// receives a terminal update (See TaskState in v1/mesos.proto) for
// it. If the task is unknown to the master, a TASK_LOST update is
// generated.
//
// If a task within a task group is killed before the group is
// delivered to the executor, all tasks in the task group are
// killed. When a task group has been delivered to the executor,
// it is up to the executor to decide how to deal with the kill.
// Note The default Mesos executor will currently kill all the
// tasks in the task group if it gets a kill for any task.
type Call_Kill struct {
	TaskId  *mesos_v1.TaskID  `protobuf:"bytes,1,req,name=task_id,json=task_id" json:"task_id,omitempty"`
	AgentId *mesos_v1.AgentID `protobuf:"bytes,2,opt,name=agent_id,json=agent_id" json:"agent_id,omitempty"`
	// If set, overrides any previously specified kill policy for this task.
	// This includes 'TaskInfo.kill_policy' and 'Executor.kill.kill_policy'.
	// Can be used to forcefully kill a task which is already being killed.
	KillPolicy       *mesos_v1.KillPolicy `protobuf:"bytes,3,opt,name=kill_policy,json=kill_policy" json:"kill_policy,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *Call_Kill) Reset()                    { *m = Call_Kill{} }
func (m *Call_Kill) String() string            { return proto.CompactTextString(m) }
func (*Call_Kill) ProtoMessage()               {}
func (*Call_Kill) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 6} }

func (m *Call_Kill) GetTaskId() *mesos_v1.TaskID {
	if m != nil {
		return m.TaskId
	}
	return nil
}

func (m *Call_Kill) GetAgentId() *mesos_v1.AgentID {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *Call_Kill) GetKillPolicy() *mesos_v1.KillPolicy {
	if m != nil {
		return m.KillPolicy
	}
	return nil
}

// Shuts down a custom executor. When the executor gets a shutdown
// event, it is expected to kill all its tasks (and send TASK_KILLED
// updates) and terminate. If the executor doesn’t terminate within
// a certain timeout (configurable via
// '--executor_shutdown_grace_period' agent flag), the agent will
// forcefully destroy the container (executor and its tasks) and
// transition its active tasks to TASK_LOST.
type Call_Shutdown struct {
	ExecutorId       *mesos_v1.ExecutorID `protobuf:"bytes,1,req,name=executor_id,json=executor_id" json:"executor_id,omitempty"`
	AgentId          *mesos_v1.AgentID    `protobuf:"bytes,2,req,name=agent_id,json=agent_id" json:"agent_id,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *Call_Shutdown) Reset()                    { *m = Call_Shutdown{} }
func (m *Call_Shutdown) String() string            { return proto.CompactTextString(m) }
func (*Call_Shutdown) ProtoMessage()               {}
func (*Call_Shutdown) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 7} }

func (m *Call_Shutdown) GetExecutorId() *mesos_v1.ExecutorID {
	if m != nil {
		return m.ExecutorId
	}
	return nil
}

func (m *Call_Shutdown) GetAgentId() *mesos_v1.AgentID {
	if m != nil {
		return m.AgentId
	}
	return nil
}

// Acknowledges the receipt of status update. Schedulers are
// responsible for explicitly acknowledging the receipt of status
// updates that have 'Update.status().uuid()' field set. Such status
// updates are retried by the agent until they are acknowledged by
// the scheduler.
type Call_Acknowledge struct {
	AgentId          *mesos_v1.AgentID `protobuf:"bytes,1,req,name=agent_id,json=agent_id" json:"agent_id,omitempty"`
	TaskId           *mesos_v1.TaskID  `protobuf:"bytes,2,req,name=task_id,json=task_id" json:"task_id,omitempty"`
	Uuid             []byte            `protobuf:"bytes,3,req,name=uuid" json:"uuid,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Call_Acknowledge) Reset()                    { *m = Call_Acknowledge{} }
func (m *Call_Acknowledge) String() string            { return proto.CompactTextString(m) }
func (*Call_Acknowledge) ProtoMessage()               {}
func (*Call_Acknowledge) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 8} }

func (m *Call_Acknowledge) GetAgentId() *mesos_v1.AgentID {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *Call_Acknowledge) GetTaskId() *mesos_v1.TaskID {
	if m != nil {
		return m.TaskId
	}
	return nil
}

func (m *Call_Acknowledge) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

// Acknowledges the receipt of an operation status update. Schedulers
// are responsible for explicitly acknowledging the receipt of updates
// which have the 'UpdateOperationStatus.status().uuid()' field set.
// Such status updates are retried by the agent or resource provider
// until they are acknowledged by the scheduler.
type Call_AcknowledgeOperationStatus struct {
	// If the operation affects resources that belong to a SLRP, both
	// `agent_id` and `resource_provider_id` have to be set.
	//
	// If the operation affects resources that belong to a SERP, only
	// `resource_provider_id` has to be set.
	AgentId            *mesos_v1.AgentID            `protobuf:"bytes,1,opt,name=agent_id,json=agent_id" json:"agent_id,omitempty"`
	ResourceProviderId *mesos_v1.ResourceProviderID `protobuf:"bytes,2,opt,name=resource_provider_id,json=resource_provider_id" json:"resource_provider_id,omitempty"`
	Uuid               []byte                       `protobuf:"bytes,3,req,name=uuid" json:"uuid,omitempty"`
	OperationId        *mesos_v1.OperationID        `protobuf:"bytes,4,req,name=operation_id,json=operation_id" json:"operation_id,omitempty"`
	XXX_unrecognized   []byte                       `json:"-"`
}

func (m *Call_AcknowledgeOperationStatus) Reset()         { *m = Call_AcknowledgeOperationStatus{} }
func (m *Call_AcknowledgeOperationStatus) String() string { return proto.CompactTextString(m) }
func (*Call_AcknowledgeOperationStatus) ProtoMessage()    {}
func (*Call_AcknowledgeOperationStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 9}
}

func (m *Call_AcknowledgeOperationStatus) GetAgentId() *mesos_v1.AgentID {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *Call_AcknowledgeOperationStatus) GetResourceProviderId() *mesos_v1.ResourceProviderID {
	if m != nil {
		return m.ResourceProviderId
	}
	return nil
}

func (m *Call_AcknowledgeOperationStatus) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *Call_AcknowledgeOperationStatus) GetOperationId() *mesos_v1.OperationID {
	if m != nil {
		return m.OperationId
	}
	return nil
}

// Allows the scheduler to query the status for non-terminal tasks.
// This causes the master to send back the latest task status for
// each task in 'tasks', if possible. Tasks that are no longer known
// will result in a TASK_LOST, TASK_UNKNOWN, or TASK_UNREACHABLE update.
// If 'tasks' is empty, then the master will send the latest status
// for each task currently known.
type Call_Reconcile struct {
	Tasks            []*Call_Reconcile_Task `protobuf:"bytes,1,rep,name=tasks" json:"tasks,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *Call_Reconcile) Reset()                    { *m = Call_Reconcile{} }
func (m *Call_Reconcile) String() string            { return proto.CompactTextString(m) }
func (*Call_Reconcile) ProtoMessage()               {}
func (*Call_Reconcile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 10} }

func (m *Call_Reconcile) GetTasks() []*Call_Reconcile_Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

// TODO(vinod): Support arbitrary queries than just state of tasks.
type Call_Reconcile_Task struct {
	TaskId           *mesos_v1.TaskID  `protobuf:"bytes,1,req,name=task_id,json=task_id" json:"task_id,omitempty"`
	AgentId          *mesos_v1.AgentID `protobuf:"bytes,2,opt,name=agent_id,json=agent_id" json:"agent_id,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Call_Reconcile_Task) Reset()                    { *m = Call_Reconcile_Task{} }
func (m *Call_Reconcile_Task) String() string            { return proto.CompactTextString(m) }
func (*Call_Reconcile_Task) ProtoMessage()               {}
func (*Call_Reconcile_Task) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 10, 0} }

func (m *Call_Reconcile_Task) GetTaskId() *mesos_v1.TaskID {
	if m != nil {
		return m.TaskId
	}
	return nil
}

func (m *Call_Reconcile_Task) GetAgentId() *mesos_v1.AgentID {
	if m != nil {
		return m.AgentId
	}
	return nil
}

// Allows the scheduler to query the status of operations. This causes
// the master to send back the latest status for each operation in
// 'operations', if possible. If 'operations' is empty, then the
// master will send the latest status for each operation currently
// known.
type Call_ReconcileOperations struct {
	Operations       []*Call_ReconcileOperations_Operation `protobuf:"bytes,1,rep,name=operations" json:"operations,omitempty"`
	XXX_unrecognized []byte                                `json:"-"`
}

func (m *Call_ReconcileOperations) Reset()                    { *m = Call_ReconcileOperations{} }
func (m *Call_ReconcileOperations) String() string            { return proto.CompactTextString(m) }
func (*Call_ReconcileOperations) ProtoMessage()               {}
func (*Call_ReconcileOperations) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 11} }

func (m *Call_ReconcileOperations) GetOperations() []*Call_ReconcileOperations_Operation {
	if m != nil {
		return m.Operations
	}
	return nil
}

type Call_ReconcileOperations_Operation struct {
	OperationId        *mesos_v1.OperationID        `protobuf:"bytes,1,req,name=operation_id,json=operation_id" json:"operation_id,omitempty"`
	AgentId            *mesos_v1.AgentID            `protobuf:"bytes,2,opt,name=agent_id,json=agent_id" json:"agent_id,omitempty"`
	ResourceProviderId *mesos_v1.ResourceProviderID `protobuf:"bytes,3,opt,name=resource_provider_id,json=resource_provider_id" json:"resource_provider_id,omitempty"`
	XXX_unrecognized   []byte                       `json:"-"`
}

func (m *Call_ReconcileOperations_Operation) Reset()         { *m = Call_ReconcileOperations_Operation{} }
func (m *Call_ReconcileOperations_Operation) String() string { return proto.CompactTextString(m) }
func (*Call_ReconcileOperations_Operation) ProtoMessage()    {}
func (*Call_ReconcileOperations_Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 11, 0}
}

func (m *Call_ReconcileOperations_Operation) GetOperationId() *mesos_v1.OperationID {
	if m != nil {
		return m.OperationId
	}
	return nil
}

func (m *Call_ReconcileOperations_Operation) GetAgentId() *mesos_v1.AgentID {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *Call_ReconcileOperations_Operation) GetResourceProviderId() *mesos_v1.ResourceProviderID {
	if m != nil {
		return m.ResourceProviderId
	}
	return nil
}

// Sends arbitrary binary data to the executor. Note that Mesos
// neither interprets this data nor makes any guarantees about the
// delivery of this message to the executor.
type Call_Message struct {
	AgentId          *mesos_v1.AgentID    `protobuf:"bytes,1,req,name=agent_id,json=agent_id" json:"agent_id,omitempty"`
	ExecutorId       *mesos_v1.ExecutorID `protobuf:"bytes,2,req,name=executor_id,json=executor_id" json:"executor_id,omitempty"`
	Data             []byte               `protobuf:"bytes,3,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *Call_Message) Reset()                    { *m = Call_Message{} }
func (m *Call_Message) String() string            { return proto.CompactTextString(m) }
func (*Call_Message) ProtoMessage()               {}
func (*Call_Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 12} }

func (m *Call_Message) GetAgentId() *mesos_v1.AgentID {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *Call_Message) GetExecutorId() *mesos_v1.ExecutorID {
	if m != nil {
		return m.ExecutorId
	}
	return nil
}

func (m *Call_Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// Requests a specific set of resources from Mesos's allocator. If
// the allocator has support for this, corresponding offers will be
// sent asynchronously via the OFFERS event(s).
//
// NOTE: The built-in hierarchical allocator doesn't have support
// for this call and hence simply ignores it.
type Call_Request struct {
	Requests         []*mesos_v1.Request `protobuf:"bytes,1,rep,name=requests" json:"requests,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Call_Request) Reset()                    { *m = Call_Request{} }
func (m *Call_Request) String() string            { return proto.CompactTextString(m) }
func (*Call_Request) ProtoMessage()               {}
func (*Call_Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 13} }

func (m *Call_Request) GetRequests() []*mesos_v1.Request {
	if m != nil {
		return m.Requests
	}
	return nil
}

// Suppress offers for the specified roles. If `roles` is empty,
// the `SUPPRESS` call will suppress offers for all of the roles
// the framework is currently subscribed to.
type Call_Suppress struct {
	Roles            []string `protobuf:"bytes,1,rep,name=roles" json:"roles,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Call_Suppress) Reset()                    { *m = Call_Suppress{} }
func (m *Call_Suppress) String() string            { return proto.CompactTextString(m) }
func (*Call_Suppress) ProtoMessage()               {}
func (*Call_Suppress) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 14} }

func (m *Call_Suppress) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "mesos.v1.scheduler.Event")
	proto.RegisterType((*Event_Subscribed)(nil), "mesos.v1.scheduler.Event.Subscribed")
	proto.RegisterType((*Event_Offers)(nil), "mesos.v1.scheduler.Event.Offers")
	proto.RegisterType((*Event_InverseOffers)(nil), "mesos.v1.scheduler.Event.InverseOffers")
	proto.RegisterType((*Event_Rescind)(nil), "mesos.v1.scheduler.Event.Rescind")
	proto.RegisterType((*Event_RescindInverseOffer)(nil), "mesos.v1.scheduler.Event.RescindInverseOffer")
	proto.RegisterType((*Event_Update)(nil), "mesos.v1.scheduler.Event.Update")
	proto.RegisterType((*Event_UpdateOperationStatus)(nil), "mesos.v1.scheduler.Event.UpdateOperationStatus")
	proto.RegisterType((*Event_Message)(nil), "mesos.v1.scheduler.Event.Message")
	proto.RegisterType((*Event_Failure)(nil), "mesos.v1.scheduler.Event.Failure")
	proto.RegisterType((*Event_Error)(nil), "mesos.v1.scheduler.Event.Error")
	proto.RegisterType((*Response)(nil), "mesos.v1.scheduler.Response")
	proto.RegisterType((*Response_ReconcileOperations)(nil), "mesos.v1.scheduler.Response.ReconcileOperations")
	proto.RegisterType((*Call)(nil), "mesos.v1.scheduler.Call")
	proto.RegisterType((*Call_Subscribe)(nil), "mesos.v1.scheduler.Call.Subscribe")
	proto.RegisterType((*Call_Accept)(nil), "mesos.v1.scheduler.Call.Accept")
	proto.RegisterType((*Call_Decline)(nil), "mesos.v1.scheduler.Call.Decline")
	proto.RegisterType((*Call_AcceptInverseOffers)(nil), "mesos.v1.scheduler.Call.AcceptInverseOffers")
	proto.RegisterType((*Call_DeclineInverseOffers)(nil), "mesos.v1.scheduler.Call.DeclineInverseOffers")
	proto.RegisterType((*Call_Revive)(nil), "mesos.v1.scheduler.Call.Revive")
	proto.RegisterType((*Call_Kill)(nil), "mesos.v1.scheduler.Call.Kill")
	proto.RegisterType((*Call_Shutdown)(nil), "mesos.v1.scheduler.Call.Shutdown")
	proto.RegisterType((*Call_Acknowledge)(nil), "mesos.v1.scheduler.Call.Acknowledge")
	proto.RegisterType((*Call_AcknowledgeOperationStatus)(nil), "mesos.v1.scheduler.Call.AcknowledgeOperationStatus")
	proto.RegisterType((*Call_Reconcile)(nil), "mesos.v1.scheduler.Call.Reconcile")
	proto.RegisterType((*Call_Reconcile_Task)(nil), "mesos.v1.scheduler.Call.Reconcile.Task")
	proto.RegisterType((*Call_ReconcileOperations)(nil), "mesos.v1.scheduler.Call.ReconcileOperations")
	proto.RegisterType((*Call_ReconcileOperations_Operation)(nil), "mesos.v1.scheduler.Call.ReconcileOperations.Operation")
	proto.RegisterType((*Call_Message)(nil), "mesos.v1.scheduler.Call.Message")
	proto.RegisterType((*Call_Request)(nil), "mesos.v1.scheduler.Call.Request")
	proto.RegisterType((*Call_Suppress)(nil), "mesos.v1.scheduler.Call.Suppress")
	proto.RegisterEnum("mesos.v1.scheduler.Event_Type", Event_Type_name, Event_Type_value)
	proto.RegisterEnum("mesos.v1.scheduler.Response_Type", Response_Type_name, Response_Type_value)
	proto.RegisterEnum("mesos.v1.scheduler.Call_Type", Call_Type_name, Call_Type_value)
}

func init() { proto.RegisterFile("scheduler.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1754 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0x4b, 0x73, 0xdb, 0x46,
	0x12, 0x5e, 0x50, 0x7c, 0x36, 0x25, 0x0a, 0x1a, 0x3d, 0x0c, 0xc3, 0x2f, 0x9a, 0xe5, 0x2a, 0xc9,
	0xb5, 0x36, 0xbd, 0xd2, 0x96, 0x1f, 0x6b, 0xaf, 0xb6, 0x96, 0x22, 0x21, 0x1b, 0x6b, 0x99, 0xe4,
	0x0e, 0x48, 0xed, 0x11, 0x0b, 0x13, 0x43, 0x09, 0x25, 0x8a, 0xe0, 0x02, 0x20, 0xbd, 0xde, 0xdb,
	0xfa, 0x90, 0x9f, 0x90, 0x73, 0x8e, 0xa9, 0xca, 0x31, 0xc7, 0xdc, 0x92, 0x4b, 0x2e, 0xf9, 0x1f,
	0xf9, 0x17, 0x49, 0xcd, 0x60, 0x00, 0x82, 0x24, 0x48, 0x4a, 0xa9, 0x4a, 0x2a, 0x37, 0x60, 0xe6,
	0xeb, 0x9e, 0x46, 0xa3, 0xfb, 0x9b, 0xaf, 0x61, 0xdd, 0xed, 0x9c, 0x13, 0x73, 0xd8, 0x23, 0x4e,
	0x79, 0xe0, 0xd8, 0x9e, 0x8d, 0xd0, 0x25, 0x71, 0x6d, 0xb7, 0x3c, 0xda, 0x2f, 0x87, 0x3b, 0xf2,
	0x16, 0x5b, 0x7b, 0x32, 0xda, 0x7f, 0xe2, 0x6f, 0x32, 0x64, 0xe9, 0x87, 0x02, 0xa4, 0x94, 0x11,
	0xe9, 0x7b, 0xe8, 0x00, 0x92, 0xde, 0xc7, 0x01, 0x91, 0x84, 0xa2, 0xb0, 0x57, 0x38, 0xb8, 0x5b,
	0x9e, 0x75, 0x51, 0x66, 0xc0, 0x72, 0xeb, 0xe3, 0x80, 0x60, 0x86, 0x45, 0x35, 0x00, 0x77, 0xf8,
	0xde, 0xed, 0x38, 0xd6, 0x7b, 0x62, 0x4a, 0x89, 0xa2, 0xb0, 0x97, 0x3f, 0x78, 0x30, 0xdf, 0x52,
	0x0b, 0xb1, 0x38, 0x62, 0x87, 0x5e, 0x40, 0xda, 0xee, 0x76, 0x89, 0xe3, 0x4a, 0x2b, 0xcc, 0x43,
	0x71, 0xbe, 0x87, 0x06, 0xc3, 0x61, 0x8e, 0x47, 0x75, 0x28, 0x58, 0xfd, 0x11, 0x71, 0x5c, 0xa2,
	0x73, 0x0f, 0x39, 0xe6, 0x61, 0x77, 0xbe, 0x07, 0xd5, 0xc7, 0x73, 0x47, 0x6b, 0x56, 0xf4, 0x15,
	0xbd, 0x82, 0x8c, 0x43, 0xdc, 0x8e, 0xd5, 0x37, 0xa5, 0x24, 0x73, 0x74, 0x7f, 0xbe, 0x23, 0xec,
	0x03, 0x71, 0x60, 0x81, 0x0c, 0xd8, 0xe6, 0x8f, 0xfa, 0x44, 0x50, 0x12, 0x30, 0x57, 0x8f, 0x97,
	0xba, 0x8a, 0x86, 0x86, 0x37, 0x9d, 0xd9, 0x45, 0x9a, 0xa9, 0xe1, 0xc0, 0x34, 0x3c, 0x22, 0xa5,
	0x96, 0x65, 0xaa, 0xcd, 0x70, 0x98, 0xe3, 0xd1, 0x19, 0xdc, 0xf0, 0x9f, 0x74, 0x7b, 0x40, 0x1c,
	0xc3, 0xb3, 0xec, 0xbe, 0xee, 0x7a, 0x86, 0x37, 0x74, 0xa5, 0x3c, 0x73, 0xf5, 0x64, 0x99, 0xab,
	0x46, 0x60, 0xa7, 0x31, 0x33, 0xbc, 0x3d, 0x8c, 0x5b, 0xa6, 0x29, 0xbc, 0x24, 0xae, 0x6b, 0x9c,
	0x11, 0x29, 0xbd, 0x2c, 0x85, 0xef, 0x7c, 0x20, 0x0e, 0x2c, 0xa8, 0x71, 0xd7, 0xb0, 0x7a, 0x43,
	0x87, 0x48, 0x99, 0x65, 0xc6, 0xc7, 0x3e, 0x10, 0x07, 0x16, 0xe8, 0x29, 0xa4, 0x88, 0xe3, 0xd8,
	0x8e, 0x94, 0x65, 0xa6, 0xf7, 0xe6, 0x9b, 0x2a, 0x14, 0x86, 0x7d, 0xb4, 0xfc, 0x8d, 0x00, 0xa0,
	0x45, 0x8b, 0x71, 0xb5, 0xeb, 0x18, 0x97, 0xe4, 0x83, 0xed, 0x5c, 0xe8, 0x96, 0x29, 0x09, 0xc5,
	0xc4, 0x5e, 0xfe, 0x60, 0x7b, 0xec, 0xec, 0x38, 0xd8, 0x55, 0x6b, 0x38, 0x1f, 0x42, 0x55, 0x13,
	0xfd, 0x15, 0xe4, 0x73, 0x62, 0x38, 0xde, 0x7b, 0x62, 0x78, 0xba, 0xd5, 0xf7, 0x88, 0x33, 0x32,
	0x7a, 0xba, 0x4b, 0x3a, 0x76, 0xdf, 0x74, 0x59, 0x73, 0x08, 0x58, 0x0a, 0x11, 0x2a, 0x07, 0x68,
	0xfe, 0x3e, 0x7a, 0x0a, 0xf9, 0x4b, 0xc3, 0xf5, 0x88, 0xa3, 0x5b, 0xfd, 0xae, 0xcd, 0x3b, 0x61,
	0x6b, 0x7c, 0xec, 0x3b, 0xb6, 0xa9, 0xf6, 0xbb, 0x36, 0x86, 0xcb, 0xf0, 0x59, 0xde, 0x87, 0x34,
	0xaf, 0xdd, 0xdd, 0xb0, 0x8b, 0x84, 0xe2, 0xca, 0x5e, 0xfe, 0x60, 0x7d, 0x6c, 0xeb, 0x57, 0x14,
	0xdf, 0x96, 0xeb, 0xb0, 0x36, 0xd1, 0x04, 0xe8, 0x70, 0xa6, 0x8b, 0x7c, 0x0f, 0x3b, 0x63, 0x0f,
	0x13, 0xa5, 0x39, 0xd9, 0x34, 0xf2, 0x73, 0xc8, 0xf0, 0x02, 0x46, 0x8f, 0x20, 0xcb, 0x3c, 0x8c,
	0x13, 0xb7, 0x31, 0x15, 0x85, 0x5a, 0xc3, 0x19, 0x06, 0x51, 0x4d, 0x19, 0xc3, 0x66, 0x4c, 0xe5,
	0xa3, 0x57, 0x20, 0x4e, 0x84, 0xb3, 0xd0, 0x59, 0x21, 0x1a, 0x8b, 0x6a, 0xca, 0xcf, 0x20, 0xed,
	0x97, 0x2b, 0x7a, 0x04, 0x69, 0x5e, 0xe0, 0xbe, 0x71, 0x24, 0x97, 0x2d, 0xc3, 0xbd, 0xe0, 0x55,
	0xcc, 0x31, 0xf2, 0x3f, 0x60, 0x3b, 0xb6, 0xcc, 0xd1, 0xfe, 0x94, 0x9b, 0x9b, 0x91, 0x18, 0xa6,
	0x3a, 0x22, 0xf0, 0xf5, 0x49, 0x80, 0x0c, 0x2f, 0x6d, 0x9a, 0x11, 0xe3, 0x8c, 0xf4, 0xbd, 0xd8,
	0x8f, 0xa8, 0xd0, 0x1d, 0x9a, 0x11, 0x06, 0x51, 0x4d, 0x5a, 0x04, 0xe4, 0xbf, 0xa4, 0x33, 0xf4,
	0x6c, 0xf6, 0xd5, 0x89, 0xe9, 0xc0, 0x15, 0xbe, 0xa9, 0xd6, 0x30, 0x04, 0x40, 0xd5, 0x44, 0x08,
	0x92, 0xa6, 0xe1, 0x19, 0xd2, 0x4a, 0x31, 0xb1, 0xb7, 0x8a, 0xd9, 0xb3, 0xfc, 0x99, 0x00, 0x19,
	0xde, 0x22, 0x53, 0x41, 0x08, 0xd7, 0x0d, 0x42, 0xb8, 0x52, 0x10, 0x3b, 0x61, 0xa2, 0x68, 0xed,
	0xa6, 0xc2, 0x6c, 0xdc, 0x87, 0x14, 0xeb, 0x37, 0x24, 0x8d, 0x99, 0x81, 0x66, 0x22, 0x17, 0xb6,
	0x7d, 0xe9, 0x7b, 0x01, 0x92, 0xf4, 0x56, 0x41, 0x79, 0xc8, 0xb4, 0xeb, 0x6f, 0xeb, 0x8d, 0x7f,
	0xd5, 0xc5, 0x3f, 0xa0, 0x02, 0x80, 0xd6, 0x3e, 0xd2, 0xaa, 0x58, 0x3d, 0x52, 0x6a, 0xa2, 0x80,
	0x00, 0xd2, 0x8d, 0xe3, 0x63, 0x05, 0x6b, 0x62, 0x02, 0x21, 0x28, 0xa8, 0xf5, 0x53, 0x05, 0x6b,
	0x8a, 0xce, 0xd7, 0x72, 0xd4, 0x18, 0x2b, 0x5a, 0x55, 0xad, 0xd7, 0xc4, 0x15, 0x74, 0x13, 0xb6,
	0xf9, 0x8b, 0x3e, 0x01, 0x14, 0x81, 0xfa, 0x69, 0x37, 0x6b, 0x95, 0x96, 0x22, 0x26, 0xd1, 0x2d,
	0xb8, 0xe1, 0x3f, 0xeb, 0x8d, 0xa6, 0x82, 0x2b, 0x2d, 0xb5, 0x51, 0xd7, 0xb5, 0x56, 0xa5, 0xd5,
	0xd6, 0xc4, 0x3c, 0x75, 0xf8, 0x4e, 0xd1, 0xb4, 0xca, 0x6b, 0x45, 0x4c, 0xd1, 0x97, 0xe3, 0x8a,
	0x7a, 0xd2, 0xc6, 0x8a, 0x98, 0x46, 0x39, 0x48, 0x29, 0x18, 0x37, 0xb0, 0x98, 0x41, 0x6b, 0x90,
	0x7b, 0xa3, 0x54, 0x70, 0xeb, 0x48, 0xa9, 0xb4, 0xc4, 0x6c, 0xe9, 0x27, 0x01, 0xb2, 0x98, 0xb8,
	0x03, 0xbb, 0xef, 0x12, 0xd4, 0x81, 0x2d, 0x87, 0xb6, 0x77, 0xc7, 0xea, 0x45, 0x78, 0xd7, 0xe5,
	0xff, 0xe0, 0x4f, 0x71, 0x04, 0x15, 0xd8, 0x96, 0x71, 0x60, 0x18, 0x56, 0x99, 0x4b, 0xef, 0x84,
	0x99, 0x45, 0x59, 0xa7, 0x5d, 0x34, 0xb3, 0x8c, 0xde, 0x00, 0x9a, 0x66, 0x7a, 0x12, 0x34, 0xf6,
	0x82, 0x1a, 0xde, 0xb0, 0x27, 0x17, 0x88, 0x5b, 0x7a, 0x1c, 0xf7, 0x73, 0x24, 0xd8, 0xc2, 0x4a,
	0xb5, 0x51, 0xaf, 0xaa, 0x27, 0x91, 0xdc, 0x69, 0xa2, 0x50, 0xfa, 0xf6, 0x16, 0x24, 0xab, 0x46,
	0xaf, 0x17, 0xc3, 0xa4, 0xc2, 0x15, 0x99, 0x74, 0x9f, 0x4b, 0x91, 0x04, 0x93, 0x22, 0x77, 0xe2,
	0xf2, 0x44, 0x4f, 0x88, 0x2a, 0x91, 0xbf, 0x43, 0x2e, 0x54, 0x14, 0x9c, 0x3c, 0x4b, 0x73, 0xed,
	0x42, 0xba, 0xc7, 0x63, 0x23, 0xf4, 0x1c, 0xd2, 0x46, 0xa7, 0x43, 0x06, 0x1e, 0xbf, 0xfa, 0xef,
	0xcd, 0x35, 0xaf, 0x30, 0x18, 0xe6, 0x70, 0xf4, 0x12, 0x32, 0x26, 0xe9, 0xf4, 0xac, 0xfe, 0xc2,
	0x5b, 0x99, 0x59, 0xd6, 0x7c, 0x1c, 0x0e, 0x0c, 0xd0, 0xbf, 0x61, 0xdb, 0xf7, 0xa2, 0x4f, 0x31,
	0xf0, 0x1a, 0xf3, 0xf4, 0x68, 0x49, 0x0c, 0x93, 0x62, 0x66, 0xd3, 0x98, 0x5d, 0x44, 0x1d, 0xd8,
	0xe1, 0x87, 0x4d, 0x1f, 0x51, 0x98, 0x2f, 0x4b, 0xa2, 0xc1, 0x4e, 0x9e, 0xb1, 0x65, 0xc6, 0xac,
	0xd2, 0xdc, 0x39, 0x64, 0x64, 0x8d, 0x88, 0xb4, 0xbe, 0x24, 0x77, 0x98, 0xc1, 0x30, 0x87, 0xd3,
	0x3f, 0x7d, 0x61, 0xf5, 0x7a, 0x5c, 0x2a, 0xcc, 0xff, 0xd3, 0x6f, 0xad, 0x5e, 0x0f, 0x33, 0x28,
	0x3a, 0x84, 0xac, 0x7b, 0x3e, 0xf4, 0x4c, 0xfb, 0x43, 0x7f, 0x91, 0x48, 0xf0, 0x7f, 0x34, 0x07,
	0xe2, 0xd0, 0x04, 0x1d, 0x43, 0xde, 0xe8, 0x5c, 0xf4, 0xed, 0x0f, 0x3d, 0x62, 0x9e, 0x11, 0xae,
	0x15, 0x1e, 0x2c, 0xc8, 0x73, 0x88, 0xc5, 0x51, 0x43, 0x34, 0x84, 0xdb, 0x91, 0xd7, 0x59, 0x55,
	0xb5, 0xc1, 0x1c, 0xff, 0xf9, 0x2a, 0x8e, 0xa7, 0x7b, 0x50, 0x36, 0xe6, 0xee, 0xd1, 0x3a, 0x0f,
	0x49, 0x80, 0x8b, 0xdd, 0xd2, 0x82, 0x64, 0x73, 0x24, 0x1e, 0x1b, 0x21, 0x7d, 0x0e, 0x29, 0xa1,
	0x25, 0x15, 0x77, 0x55, 0x42, 0xa2, 0xfd, 0x10, 0xf0, 0x3c, 0x2c, 0xe9, 0x87, 0x19, 0x01, 0xf8,
	0x92, 0x0a, 0xf0, 0xff, 0x0c, 0x89, 0xeb, 0x71, 0x59, 0x5a, 0x5c, 0x10, 0x0f, 0xc3, 0xe1, 0xc0,
	0x80, 0x15, 0xc6, 0x70, 0x30, 0x70, 0x88, 0xeb, 0x4a, 0xe2, 0xb2, 0xc2, 0xe0, 0x40, 0x1c, 0x9a,
	0xc8, 0x23, 0xc8, 0x85, 0xbc, 0x80, 0xfe, 0x06, 0x85, 0x08, 0x77, 0x51, 0x41, 0xe6, 0x5f, 0xde,
	0x37, 0xe2, 0xd8, 0x8b, 0x6a, 0xb2, 0xb5, 0x6e, 0xf4, 0x15, 0x3d, 0x04, 0x31, 0x70, 0x4c, 0x4c,
	0xdd, 0xb1, 0x7b, 0x84, 0x2a, 0xc0, 0x95, 0xbd, 0x1c, 0x5e, 0x1f, 0xaf, 0x63, 0xba, 0x2c, 0x7f,
	0x21, 0x40, 0xda, 0xef, 0x66, 0x54, 0x86, 0x5c, 0xa0, 0x78, 0x02, 0xaa, 0x8e, 0x91, 0x3c, 0x59,
	0xae, 0x9f, 0x5c, 0xf4, 0x17, 0x80, 0xc8, 0x0f, 0x4c, 0xcc, 0x70, 0x3b, 0xc5, 0x8d, 0x19, 0x1e,
	0x47, 0xc0, 0xe8, 0x8f, 0x90, 0xe9, 0x5a, 0x3d, 0x6f, 0x3c, 0x74, 0x45, 0x0e, 0x3a, 0xf6, 0x37,
	0x70, 0x80, 0x90, 0xbb, 0x90, 0xe1, 0x64, 0x70, 0xed, 0x10, 0x23, 0xe7, 0x24, 0x96, 0x9e, 0xf3,
	0x7f, 0x01, 0x36, 0x63, 0x88, 0x0d, 0x1d, 0xc2, 0xc6, 0xb4, 0x22, 0x5c, 0x70, 0xf8, 0xfa, 0xa4,
	0x24, 0xbc, 0x66, 0x0c, 0x9f, 0x04, 0xd8, 0x8a, 0x63, 0xbe, 0xdf, 0x34, 0x88, 0xbb, 0x90, 0xf6,
	0x89, 0x12, 0x6d, 0x41, 0xca, 0xaf, 0x1e, 0x81, 0x55, 0x8f, 0xff, 0x22, 0x7f, 0x2e, 0x40, 0x92,
	0x52, 0x22, 0x7a, 0x08, 0x19, 0xcf, 0x70, 0x23, 0x83, 0x8a, 0x38, 0xa9, 0x72, 0xd5, 0x1a, 0x4e,
	0x53, 0x80, 0x6a, 0x4e, 0x88, 0xc0, 0xc4, 0x55, 0x44, 0x20, 0x65, 0x5b, 0x7d, 0x60, 0xf7, 0xac,
	0xce, 0xc7, 0xd9, 0x71, 0x84, 0x9e, 0xde, 0x64, 0x7b, 0x18, 0x2e, 0xc2, 0x67, 0xd9, 0x86, 0x6c,
	0xc0, 0xb9, 0xd3, 0x3a, 0x52, 0xb8, 0xa2, 0x98, 0x9d, 0x8c, 0x73, 0x89, 0x62, 0x96, 0xff, 0x07,
	0xf9, 0x08, 0x93, 0x5e, 0x53, 0x6e, 0x47, 0xb2, 0x97, 0x58, 0x92, 0x3d, 0x04, 0xc9, 0xe1, 0xd0,
	0x32, 0x03, 0x89, 0x4d, 0x9f, 0xe5, 0x1f, 0x05, 0x90, 0xe7, 0xd3, 0xf8, 0x35, 0x55, 0x77, 0x9d,
	0xd2, 0xb2, 0x6b, 0x0f, 0x9d, 0x0e, 0xd1, 0x07, 0x8e, 0x3d, 0xb2, 0x4c, 0x12, 0x91, 0xdf, 0xb7,
	0xc7, 0x96, 0x98, 0xa3, 0x9a, 0x1c, 0xa4, 0xd6, 0x30, 0x72, 0xa6, 0xd7, 0x62, 0x03, 0xa6, 0x8a,
	0x6c, 0x7c, 0x4f, 0x59, 0xa6, 0x94, 0x9c, 0x9e, 0x6d, 0xc3, 0x4f, 0xa0, 0x8a, 0x2c, 0x84, 0xaa,
	0xa6, 0xfc, 0x95, 0x00, 0xb9, 0xf0, 0x02, 0x40, 0x87, 0x90, 0xa2, 0x69, 0x09, 0xca, 0x7f, 0x77,
	0xf9, 0x9d, 0xc1, 0xd2, 0x89, 0x7d, 0x2b, 0x59, 0x87, 0x24, 0x7d, 0xfd, 0xd5, 0x8a, 0x57, 0xfe,
	0x3a, 0x11, 0xaf, 0x89, 0x4f, 0x27, 0xf8, 0xd2, 0x0f, 0xfe, 0xd9, 0x75, 0x2e, 0xbc, 0x78, 0x32,
	0x95, 0xbf, 0x13, 0x20, 0x17, 0xee, 0xcc, 0x64, 0x59, 0xb8, 0x6a, 0x96, 0xaf, 0xd9, 0xa2, 0xf3,
	0x2a, 0x66, 0xe5, 0x97, 0x55, 0xcc, 0xef, 0x63, 0x6c, 0x7d, 0x01, 0x19, 0x7e, 0xb1, 0xa3, 0xc7,
	0x90, 0xe5, 0x57, 0x7b, 0x0c, 0xcf, 0x06, 0xb7, 0x7f, 0x08, 0x91, 0x8b, 0x90, 0x0d, 0x6e, 0xf5,
	0x78, 0xd6, 0x2c, 0x7d, 0x99, 0x88, 0x9b, 0x64, 0xd6, 0x20, 0x17, 0x8e, 0x99, 0xa2, 0x80, 0x56,
	0x21, 0xdb, 0x52, 0x2a, 0xb8, 0x46, 0x37, 0x13, 0x74, 0x56, 0xac, 0x54, 0xab, 0x4a, 0xb3, 0x25,
	0xae, 0x50, 0xab, 0x9a, 0x52, 0x3d, 0x51, 0xeb, 0x74, 0x70, 0xbc, 0x09, 0xdb, 0xfe, 0x86, 0x3e,
	0x35, 0x87, 0xae, 0x21, 0x19, 0x76, 0x38, 0x6e, 0x7a, 0xaf, 0x40, 0xfd, 0x61, 0xe5, 0x54, 0x3d,
	0xa5, 0x13, 0x65, 0x16, 0x92, 0x6f, 0xd5, 0x93, 0x13, 0x31, 0x4d, 0xcf, 0xd4, 0xde, 0xb4, 0x5b,
	0xec, 0xcc, 0x0c, 0x5a, 0x87, 0x7c, 0xa5, 0x4a, 0xa3, 0x3b, 0x51, 0x6a, 0xaf, 0x15, 0x31, 0x8b,
	0x8a, 0x70, 0x3b, 0xb2, 0x30, 0x3b, 0xa9, 0xae, 0xd3, 0x6f, 0x08, 0xa7, 0x31, 0x31, 0x37, 0x77,
	0x38, 0x13, 0xa3, 0x23, 0x2d, 0xf8, 0x03, 0xf3, 0x3f, 0xdb, 0x8a, 0xd6, 0x12, 0xf3, 0x2c, 0x86,
	0x76, 0xb3, 0x89, 0x15, 0x4d, 0x13, 0x57, 0x8f, 0x76, 0xe1, 0x8e, 0xed, 0x9c, 0x95, 0x8d, 0x81,
	0xd1, 0x39, 0x27, 0x31, 0x1d, 0x72, 0x94, 0x6e, 0x3a, 0xb6, 0x67, 0xbb, 0x3f, 0x07, 0x00, 0x00,
	0xff, 0xff, 0x6e, 0x80, 0x95, 0x94, 0x7b, 0x16, 0x00, 0x00,
}
